//
//  NewsfeedModels.swift
//  VKNewsFeed
//
//  Created by Alex Kiritsa on 26.03.2020.
//  Copyright (c) 2020 Alex Kiritsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Newsfeed
{
  // MARK: Use cases
  
  enum Model
  {
    struct Request
    {
        enum RequestType {
            case getFeed
        }
    }
    struct Response
    {
        enum ResonseType {
            case presentNewsfeed
        }
    }
    struct ViewModel
    {
        enum ViewModelData {
            case displayNewfeed
        }
    }
  }
}
