//
//  NewsfeedInteractor.swift
//  VKNewsFeed
//
//  Created by Alex Kiritsa on 26.03.2020.
//  Copyright (c) 2020 Alex Kiritsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsfeedBusinessLogic
{
    func makeRequest(request: Newsfeed.Model.Request.RequestType)
}

protocol NewsfeedDataStore
{
  //var name: String { get set }
}

class NewsfeedInteractor: NewsfeedBusinessLogic, NewsfeedDataStore
{
  var presenter: NewsfeedPresentationLogic?
  var worker: NewsfeedWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func makeRequest(request: Newsfeed.Model.Request.RequestType)
  {
    worker = NewsfeedWorker()
    worker?.doSomeWork()
    
//    let response = Newsfeed.Model.Response.ResonseType()
//    presenter?.presentSomething(response: response)
    
    switch request {
    case .getFeed:
        print(".getFeed Interactor")
        presenter?.presentSomething(response: .presentNewsfeed)
    }
  }
}
