//
//  NewsfeedModels.swift
//  VKNewsFeed
//
//  Created by Alex Kiritsa on 26.03.2020.
//  Copyright (c) 2020 Alex Kiritsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Newsfeed
{
  // MARK: Use cases
  
  enum Model
  {
    struct Request
    {
        enum RequestType {
            case getNewsFeed
            case revealPostIds(postId: Int)
        }
    }
    struct Response
    {
        enum ResonseType {
            case presentNewsfeed(feed: FeedResponse, revealedPostIds: [Int])
        }
    }
    struct ViewModel
    {
        enum ViewModelData {
            case displayNewfeed(feedViewMode: FeedViewModel)
        }
    }
  }
}

struct FeedViewModel {
    struct Cell: FeedCellViewModel {
        var postId: Int
        var iconUrlString: String
        var name: String
        var date: String
        var text: String?
        var likes: String?
        var comments: String?
        var shares: String?
        var views: String?
        var photoAttachement: FeedCellPhotoAttachementViewModel?
        var sizes: FeedCellSizes
    }
    
    struct FeedCellPhotoAttachement: FeedCellPhotoAttachementViewModel {
        var photoUrlString: String?
        var width: Int
        var height: Int
    }
    let cells: [Cell]
}
